name: Data update

on:
  workflow_dispatch:

jobs:
  build:
    name: Gather data
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        pip install beautifulsoup4
        pip install html5lib
    - name: Query data
      run: |
        python code/update_data.py
    - name: Commit results to this repository
      continue-on-error: true
      run: |
        git config --global user.name 'Run bot'
        git config --global user.email 'eibanez@users.noreply.github.com'
        git add docs
        git commit -am "Automated update of data"
        git push
